[package]
name = "extender-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "extender"
path = "src/main.rs"

[dependencies]
extender-common = { path = "../extender-common" }
extender-server = { path = "../extender-server" }
extender-client = { path = "../extender-client" }
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
